// 多稼十分钟生活圈点位数据。
// 新增或删除地点时只需要维护本文件；需要显示“新增”徽标的地点请设置 isNew: true。
// lng / lat 使用高德 GCJ-02 坐标；baiduLng / baiduLat 预留给百度地图。
window.POINTS_DATA = [
  {
    "id": "swimming-pool",
    "name": "XYGYM馨园健身(馨园健身游泳会所)",
    "address": "上海市黄浦区南仓街118号馨园小区5号楼对面花园中心",
    "lng": 121.500093,
    "lat": 31.212716,
    "baiduLng": null,
    "baiduLat": null,
    "category": "leisure",
    "x": 33.2,
    "y": 47.3,
    "hitSize": 26
  },
  {
    "id": "employment",
    "name": "小东门街道就业服务站",
    "address": "上海市黄浦区中华路518弄16号",
    "lng": 121.498706,
    "lat": 31.217481,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": 24.6,
    "y": 11.7,
    "hitSize": 28
  },
  {
    "id": "xiaonanmen-metro",
    "name": "小南门地铁站",
    "address": "上海市黄浦区中华路/王家码头路",
    "image": "assets/points/xiaonanmen-metro.webp",
    "imageAlt": "上海地铁9号线小南门站1号口",
    "imageCaption": "小南门地铁站 · 1号口",
    "imageCredit": "Kmchang28",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Exit_1_of_Xiaonanmen_Station_in_Shanghai.jpg",
    "imageLicense": "CC BY-SA 4.0",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "lng": 121.498421,
    "lat": 31.216756,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": 21.1,
    "y": 17.9,
    "hitSize": 34
  },
  {
    "id": "jingzhonglou",
    "name": "小南门警钟楼",
    "address": "上海市黄浦区中华路579号(小南门地铁站2号口步行60米)",
    "image": "assets/points/jingzhonglou.webp",
    "imageAlt": "小南门警钟楼外观",
    "imageCaption": "小南门警钟楼 · 2016年影像",
    "imageCredit": "Fayhoo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Bell_Tower_at_Xiaonanmen.jpg",
    "imageLicense": "CC BY-SA 3.0",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "lng": 121.49804,
    "lat": 31.215929,
    "baiduLng": null,
    "baiduLat": null,
    "category": "memory",
    "x": 16.8,
    "y": 25.6,
    "hitSize": 30
  },
  {
    "id": "police",
    "name": "小东门派出所",
    "address": "上海市黄浦区新码头街66号",
    "lng": 121.506341,
    "lat": 31.218662,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": 70.3,
    "y": 6.3,
    "hitSize": 34
  },
  {
    "id": "sports-center",
    "name": "外滩金融都市运动中心(中山南路店)",
    "address": "上海市黄浦区中山南路609号B1层",
    "lng": 121.506148,
    "lat": 31.216467,
    "baiduLng": null,
    "baiduLat": null,
    "category": "leisure",
    "x": 71.3,
    "y": 20.5,
    "hitSize": 28
  },
  {
    "id": "huangpu-riverside",
    "name": "黄浦滨江南外滩段",
    "address": "上海市黄浦区复兴东路至南浦大桥之间的外马路沿江一侧",
    "image": "assets/routes/binjiang/stop-walkway.webp",
    "imageAlt": "黄浦滨江南外滩段步道实景",
    "imageCaption": "黄浦滨江南外滩段",
    "lng": 121.507671,
    "lat": 31.217172,
    "baiduLng": null,
    "baiduLat": null,
    "category": "leisure",
    "x": 81.1,
    "y": 17.5,
    "hitSize": 30
  },
  {
    "id": "shanghai-bank",
    "name": "上海银行(营业部)",
    "address": "上海市黄浦区中山南路688号",
    "lng": 121.503654,
    "lat": 31.215876,
    "baiduLng": null,
    "baiduLat": null,
    "category": "bussiness",
    "x": 59.2,
    "y": 22.8,
    "hitSize": 28
  },
  {
    "id": "boc",
    "name": "中国银行(南外滩支行)",
    "address": "上海市黄浦区中山南路800弄20号2层L208a、L208b、L209号",
    "lng": 121.505378,
    "lat": 31.214866,
    "baiduLng": null,
    "baiduLat": null,
    "category": "bussiness",
    "x": 65.7,
    "y": 31.2,
    "hitSize": 22
  },
  {
    "id": "bund-trendy",
    "name": "绿地·外滩潮方",
    "address": "上海市黄浦区中山南路800弄1号",
    "lng": 121.505606,
    "lat": 31.214584,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": 70.4,
    "y": 34.6,
    "hitSize": 22
  },
  {
    "id": "dongjiadu-ferry",
    "name": "董家渡渡口（轮渡站）",
    "address": "上海市黄浦区外马路737号",
    "image": "assets/routes/binjiang/stop-ferry.webp",
    "imageAlt": "黄浦江轮渡参考画面",
    "imageCaption": "黄浦江轮渡 · 参考画面",
    "lng": 121.508069,
    "lat": 31.21487,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": 84.3,
    "y": 29.1,
    "hitSize": 32
  },
  {
    "id": "dongjiadu-flower-bridge",
    "name": "董家渡路花桥",
    "address": "上海市黄浦区外滩潮方至外马路沿江一侧",
    "image": "assets/routes/binjiang/highlight-photo.webp",
    "imageAlt": "董家渡路花桥周边滨江景观",
    "imageCaption": "董家渡路花桥 · 滨江景观",
    "lng": 121.506944,
    "lat": 31.214494,
    "baiduLng": null,
    "baiduLat": null,
    "category": "leisure",
    "x": 78.8,
    "y": 37.6,
    "hitSize": 34
  },
  {
    "id": "church",
    "name": "董家渡天主堂",
    "address": "上海市黄浦区董家渡路185号",
    "image": "assets/points/church.webp",
    "imageAlt": "董家渡天主堂外立面与雕像历史照片",
    "imageCaption": "董家渡天主堂 · 历史照片",
    "imageCredit": "Michele lee",
    "imageSource": "https://commons.wikimedia.org/wiki/File:%E5%A4%A9%E4%B8%BB%E6%95%99%E4%B8%8A%E6%B5%B7%E6%95%99%E5%8D%80%E5%8D%97%E5%B8%82%E8%91%A3%E5%AE%B6%E6%B8%A1%E8%81%96%E6%96%B9%E6%BF%9F%E5%90%84%C2%B7%E6%B2%99%E5%8B%BF%E7%95%A5%E5%A0%82%E5%A4%96%E7%AB%8B%E9%9D%A2.jpg",
    "imageLicense": "CC BY-SA 3.0",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "lng": 121.504369,
    "lat": 31.214324,
    "baiduLng": null,
    "baiduLat": null,
    "category": "memory",
    "x": 59.6,
    "y": 34.4,
    "hitSize": 26
  },
  {
    "id": "duojia-committee",
    "name": "多稼居民委员会",
    "address": "上海市黄浦区会馆街66号(多稼居委会党群服务站）",
    "lng": 121.50277,
    "lat": 31.213552,
    "baiduLng": null,
    "baiduLat": null,
    "description": "社区咨询、活动报名、便民联系与党群服务。",
    "image": "assets/points/duojia-committee.webp",
    "imageAlt": "多稼居民委员会实景",
    "imageCaption": "多稼居民委员会 · 会馆街66号",
    "category": "service",
    "x": 49.4,
    "y": 41.7,
    "hitSize": 24
  },
  {
    "id": "merchants-house",
    "name": "商船会馆",
    "address": "上海市黄浦区会馆街38号",
    "lng": 121.504401,
    "lat": 31.212942,
    "baiduLng": null,
    "baiduLat": null,
    "category": "memory",
    "x": 57,
    "y": 43.9,
    "hitSize": 28
  },
  {
    "id": "ccb",
    "name": "中国建设银行(上海董家渡路支行)",
    "address": "上海市黄浦区董家渡路182号、184号、186号、188号1层",
    "lng": 121.503825,
    "lat": 31.214175,
    "baiduLng": null,
    "baiduLat": null,
    "category": "bussiness",
    "x": 53.2,
    "y": 38.4,
    "hitSize": 24
  },
  {
    "id": "cmb",
    "name": "招商银行(董家渡支行)",
    "address": "上海市黄浦区董家渡路208号1层",
    "lng": 121.503057,
    "lat": 31.214417,
    "baiduLng": null,
    "baiduLat": null,
    "category": "bussiness",
    "x": 53.2,
    "y": 38.4,
    "hitSize": 24
  },
  {
    "id": "spdb",
    "name": "浦发银行(董家渡路支行)",
    "address": "上海市黄浦区董家渡路208号1层",
    "lng": 121.502667,
    "lat": 31.214507,
    "baiduLng": null,
    "baiduLat": null,
    "category": "bussiness",
    "x": 53.2,
    "y": 38.4,
    "hitSize": 24
  },
  {
    "id": "donghao-lansheng",
    "name": "东浩兰生会展集团股份有限公司",
    "address": "上海市黄浦区董家渡路200号董家渡外滩中心T3栋47楼",
    "lng": 121.502624,
    "lat": 31.21416,
    "baiduLng": null,
    "baiduLat": null,
    "category": "bussiness",
    "x": 53.2,
    "y": 38.4,
    "hitSize": 24
  },
  {
    "id": "guotai-haitong",
    "name": "国泰海通外滩金融广场",
    "address": "上海市黄浦区中山南路888号",
    "lng": 121.505166,
    "lat": 31.213564,
    "baiduLng": null,
    "baiduLat": null,
    "category": "bussiness",
    "x": 66.6,
    "y": 40.7,
    "hitSize": 26
  },
  {
    "id": "guohai-sec",
    "name": "国海证券(中山南路营业部)",
    "address": "上海市黄浦区中山南路988号",
    "lng": 121.505066,
    "lat": 31.212811,
    "baiduLng": null,
    "baiduLat": null,
    "category": "bussiness",
    "x": 63.3,
    "y": 47,
    "hitSize": 24
  },
  {
    "id": "time-plastic",
    "name": "上海时光整形外科医院（外滩旗舰院）",
    "address": "上海市黄浦区中山南路935号",
    "lng": 121.506064,
    "lat": 31.2122,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": 70.3,
    "y": 50.4,
    "hitSize": 22
  },
  {
    "id": "qiangsheng",
    "name": "上海市强生职工医院",
    "address": "上海市黄浦区外马路984号",
    "lng": 121.506814,
    "lat": 31.211809,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": 75.8,
    "y": 52.4,
    "hitSize": 22
  },
  {
    "id": "health-center",
    "name": "小东门街道社区卫生服务中心",
    "address": "上海市黄浦区陆家浜路525号",
    "lng": 121.497989,
    "lat": 31.21231,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": 19,
    "y": 50.7,
    "hitSize": 26
  },
  {
    "id": "fabric-market",
    "name": "南外滩轻纺面料市场",
    "address": "上海市黄浦区陆家浜路399号",
    "image": "assets/points/fabric-market.webp",
    "imageAlt": "南外滩轻纺面料市场（南外滩量身定制中心）外观",
    "imageCaption": "南外滩轻纺面料市场 · 陆家浜路399号",
    "lng": 121.499716,
    "lat": 31.211674,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": 30.2,
    "y": 52.5,
    "hitSize": 28
  },
  {
    "id": "icbc",
    "name": "中国工商银行(南市支行)",
    "address": "上海市黄浦区陆家浜路275号",
    "image": "assets/points/icbc.webp",
    "imageAlt": "中国工商银行南市支行外观",
    "imageCaption": "中国工商银行（南市支行）",
    "lng": 121.501099,
    "lat": 31.210866,
    "baiduLng": null,
    "baiduLat": null,
    "category": "bussiness",
    "x": 38.4,
    "y": 59.4,
    "hitSize": 26
  },
  {
    "id": "gotterwell",
    "name": "上海歌特维康门诊部",
    "address": "上海市黄浦区中山南路1228号",
    "image": "assets/points/gotterwell.webp",
    "imageAlt": "上海歌特维康门诊部外观",
    "imageCaption": "上海歌特维康门诊部 · 中山南路1228号",
    "lng": 121.501767,
    "lat": 31.210323,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": 43,
    "y": 64.3,
    "hitSize": 28
  },
  {
    "id": "nanpu-metro",
    "name": "南浦大桥地铁站",
    "address": "上海市黄浦区中山南路/国货路",
    "image": "assets/points/nanpu-metro.webp",
    "imageAlt": "南浦大桥地铁站出入口实景",
    "imageCaption": "南浦大桥地铁站",
    "lng": 121.499725,
    "lat": 31.208504,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": 32.1,
    "y": 68.5,
    "hitSize": 34
  },
  {
    "id": "sinopec",
    "name": "中国石化齐爱加油站",
    "address": "上海市黄浦区中山南路1133号",
    "image": "assets/points/sinopec.webp",
    "imageAlt": "中国石化齐爱加油站外观",
    "imageCaption": "中国石化齐爱加油站 · 中山南路1133号",
    "lng": 121.503521,
    "lat": 31.209978,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": 53.5,
    "y": 65,
    "hitSize": 26
  },
  {
    "id": "toilet",
    "name": "南浦大桥附近公共厕所",
    "address": "上海市黄浦区南外滩环卫大楼油车码头街附近",
    "image": "assets/points/toilet.webp",
    "imageAlt": "南浦大桥附近公共厕所入口",
    "imageCaption": "南浦大桥附近公共厕所",
    "lng": 121.503037,
    "lat": 31.209229,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": 49.6,
    "y": 70.8,
    "hitSize": 30
  },
  {
    "id": "workers-gym",
    "name": "上海市总工会黄浦区工人体育馆",
    "address": "上海市黄浦区外马路1288号",
    "image": "assets/points/workers-gym.webp",
    "imageAlt": "黄浦区工人体育馆外观",
    "imageCaption": "黄浦区工人体育馆 · 外马路1288号",
    "lng": 121.503732,
    "lat": 31.207728,
    "baiduLng": null,
    "baiduLat": null,
    "category": "leisure",
    "x": 54.2,
    "y": 78.5,
    "hitSize": 30
  },
  {
    "id": "dongjiadu-road-ferry",
    "name": "陆家浜渡口（轮渡站）",
    "address": "上海市黄浦区外马路1279号",
    "image": "assets/routes/binjiang/stop-platform.webp",
    "imageAlt": "陆家浜渡口周边观景平台",
    "imageCaption": "陆家浜渡口（轮渡站）周边",
    "lng": 121.50427,
    "lat": 31.207623,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": 62.1,
    "y": 79.4,
    "hitSize": 30
  },
  {
    "id": "penglailu-second-primary-school",
    "name": "蓬莱路第二小学",
    "image": "assets/points/pllex.webp",
    "imageAlt": "蓬莱路第二小学实景",
    "imageCaption": "蓬莱路第二小学 · 多稼路199号",
    "address": "上海市黄浦区多稼路199号",
    "lng": 121.502141,
    "lat": 31.212504,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": null,
    "y": null,
    "hitSize": 30,
    "isNew": true
  },
  {
    "id": "baiqueling-group",
    "name": "百雀羚集团",
    "address": "上海市黄浦区会馆街51号绿地外滩中心T3楼25~29楼",
    "lng": 121.502796,
    "lat": 31.214084,
    "baiduLng": null,
    "baiduLat": null,
    "category": "bussiness",
    "x": null,
    "y": null,
    "hitSize": 30,
    "isNew": true
  },
  {
    "id": "dangqunfuwuzhongxin",
    "name": "小东门街道董家渡党群服务中心",
    "image": "assets/points/xdmdqfw.webp",
    "imageAlt": "小东门街道董家渡党群服务中心实景",
    "imageCaption": "小东门街道董家渡党群服务中心 · 青龙桥街66弄6号",
    "address": "上海市黄浦区青龙桥街66弄6号",
    "lng": 121.502427,
    "lat": 31.212966,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": null,
    "y": null,
    "hitSize": 30,
    "isNew": true
  },
  {
    "id": "ferry-space",
    "name": "渡口空间",
    "address": "上海市黄浦区陆家浜路18号",
    "image": "assets/routes/binjiang/ferry-space.webp",
    "imageAlt": "渡口空间建筑外观",
    "imageCaption": "渡口空间 · 陆家浜路18号",
    "lng": 121.502862,
    "lat": 31.20669,
    "baiduLng": null,
    "baiduLat": null,
    "category": "leisure",
    "x": null,
    "y": null,
    "hitSize": 30,
    "isNew": false
  },
  {
    "id": "fangyuancun",
    "name": "芳园村酒楼",
    "address": "上海市黄浦区多稼路234号",
    "lng": 121.500592,
    "lat": 31.21268,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  {
    "id": "haoxiang",
    "name": "豪祥名烟名酒",
    "address": "上海市黄浦区陆家浜路305弄4-8号阳光里",
    "lng": 121.500724,
    "lat": 31.212636,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  {
    "id": "haochuizi",
    "name": "好厨子小碗菜",
    "address": "上海市黄浦区多稼路与南仓街交叉口东南40米",
    "lng": 121.500786,
    "lat": 31.212634,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  {
    "id": "chaoshanyiniuhuoguo",
    "name": "一牛火锅",
    "address": "上海市黄浦区多稼路228号",
    "lng": 121.500884,
    "lat": 31.212572,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  {
    "id": "xiaolaoban",
    "name": "小老板海鲜酒家",
    "address": "上海市黄浦区多稼路226号",
    "lng": 121.501115,
    "lat": 31.212487,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  // {
  //   "id": "guoshuiyuguan",
  //   "name": "过水鱼馆",
  //   "address": "上海市黄浦区多稼路222号",
  //   "lng": 121.501158,
  //   "lat": 31.212449,
  //   "baiduLng": null,
  //   "baiduLat": null,
  //   "category": "shopping",
  //   "x": null,
  //   "y": null,
  //   "hitSize": 26,
  //   "isNew": false
  // },
  {
    "id": "laochengxiangtangbao",
    "name": "老城厢汤包馆",
    "address": "上海市黄浦区多稼路220号",
    "lng": 121.501217,
    "lat": 31.212437,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  {
    "id": "alishaokao",
    "name": "上海阿力烧烤",
    "address": "上海市黄浦区多稼路220号一楼",
    "lng": 121.501184,
    "lat": 31.212451,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  // {
  //   "id": "laoshanghaihuntunmian",
  //   "name": "老上海馄饨面",
  //   "address": "上海市黄浦区多稼路",
  //   "lng": 121.498506,
  //   "lat": 31.210765,
  //   "baiduLng": null,
  //   "baiduLat": null,
  //   "category": "shopping",
  //   "x": null,
  //   "y": null,
  //   "hitSize": 26,
  //   "isNew": false
  // },
  // {
  //   "id": "lanzhoulamian",
  //   "name": "兰州拉面",
  //   "address": "上海市黄浦区多稼路",
  //   "lng": 121.501142,
  //   "lat": 31.212462,
  //   "baiduLng": null,
  //   "baiduLat": null,
  //   "category": "shopping",
  //   "x": null,
  //   "y": null,
  //   "hitSize": 26,
  //   "isNew": false
  // },
  // {
  //   "id": "niuroumianyangroutang",
  //   "name": "牛肉面羊肉汤",
  //   "address": "上海市黄浦区南仓街",
  //   "lng": 121.499219,
  //   "lat": 31.210989,
  //   "baiduLng": null,
  //   "baiduLat": null,
  //   "category": "shopping",
  //   "x": null,
  //   "y": null,
  //   "hitSize": 26,
  //   "isNew": false
  // },
  {
    "id": "kuaikebianli",
    "name": "快客便利店",
    "address": "上海市黄浦区陆家浜路305弄1-3号阳光公寓",
    "lng": 121.500304,
    "lat": 31.211738,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  {
    "id": "dingzhili",
    "name": "定制里定制中心",
    "address": "上海市黄浦区南仓街187号",
    "lng": 121.500425,
    "lat": 31.212175,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  {
    "id": "haochengmingyanjiu",
    "name": "浩丞名烟名酒",
    "address": "上海市黄浦区陆家浜路305弄1-3号阳光公寓",
    "lng": 121.500183,
    "lat": 31.211612,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  {
    "id": "tonecoffee",
    "name": "t-one咖啡",
    "address": "上海市黄浦区陆家浜路305弄3-1号",
    "lng": 121.500203,
    "lat": 31.211531,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  {
    "id": "panguoxianhuntun",
    "name": "潘国仙耳光馄饨",
    "image": "assets/points/eght.webp",
    "imageAlt": "潘国仙耳光馄饨门店实景",
    "imageCaption": "潘国仙耳光馄饨 · 薛家浜路236号",
    "address": "上海市黄浦区薛家浜路236号",
    "lng": 121.502069,
    "lat": 31.210994,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  {
    "id": "kaikaizaoxing",
    "name": "凯凯造型",
    "address": "上海市黄浦区薛家浜路238号",
    "lng": 121.502033,
    "lat": 31.210884,
    "baiduLng": null,
    "baiduLat": null,
    "category": "service",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  {
    "id": "guangmingbianli",
    "name": "光明便利店",
    "address": "上海市黄浦区薛家浜路242弄1-3号",
    "lng": 121.502005,
    "lat": 31.210713,
    "baiduLng": null,
    "baiduLat": null,
    "category": "shopping",
    "x": null,
    "y": null,
    "hitSize": 26,
    "isNew": false
  },
  // {
  //   "id": "queshengyouhuo",
  //   "name": "雀巢优活",
  //   "address": "上海市黄浦区薛家浜路240号",
  //   "lng": 121.502008,
  //   "lat": 31.210733,
  //   "baiduLng": null,
  //   "baiduLat": null,
  //   "category": "shopping",
  //   "x": null,
  //   "y": null,
  //   "hitSize": 26,
  //   "isNew": false
  // },
  {
    "id": "nanpu-bridge",
    "name": "南浦大桥（浦西引桥）",
    "address": "上海市黄浦区中山南路/陆家浜路",
    "image": "assets/points/nanpu-bridge.webp",
    "imageAlt": "从浦西拍摄的南浦大桥",
    "imageCaption": "南浦大桥（浦西引桥）",
    "imageCredit": "N509FZ",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Nanpu_Bridge_from_Puxi_(20250611140720).jpg",
    "imageLicense": "CC BY-SA 4.0",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "lng": 121.501071,
    "lat": 31.209071,
    "baiduLng": null,
    "baiduLat": null,
    "category": "leisure",
    "x": 54.5,
    "y": 91.4,
    "hitSize": 34
  }
];
