[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

$scriptDirectory = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptDirectory
$photosRoot = Join-Path $projectRoot "assets\activities\photos"
$outputPath = Join-Path $projectRoot "activity-album-files.js"

$albumFolders = [ordered]@{
  "neighbor-gathering" = "Neighbor gathering"
  "parent-child-charity" = "Parent-child charity"
  "riverside-walk" = "Riverside walk"
  "traditional-culture" = "Traditional culture"
  "community-building" = "Community building"
}

$supportedExtensions = @(
  ".jpg",
  ".jpeg",
  ".png",
  ".webp",
  ".gif",
  ".avif"
)

$albumFiles = [ordered]@{}
$totalCount = 0

foreach ($album in $albumFolders.GetEnumerator()) {
  $folderPath = Join-Path $photosRoot $album.Key
  if (-not (Test-Path -LiteralPath $folderPath)) {
    New-Item -ItemType Directory -Path $folderPath -Force | Out-Null
  }

  $folderFullPath = [IO.Path]::GetFullPath($folderPath).TrimEnd([char[]]"\/")
  $files = @(
    Get-ChildItem -LiteralPath $folderPath -File -Recurse |
      Where-Object { $supportedExtensions -contains $_.Extension.ToLowerInvariant() } |
      Sort-Object FullName |
      ForEach-Object {
        $_.FullName.Substring($folderFullPath.Length).TrimStart([char[]]"\/").Replace("\", "/")
      }
  )

  $albumFiles[$album.Key] = $files
  $totalCount += $files.Count
  Write-Host ("{0}: {1} image(s)" -f $album.Value, $files.Count)
}

$json = $albumFiles | ConvertTo-Json -Depth 4 -Compress
$content = @"
// Generated by scripts/update-activity-albums.ps1. Do not edit manually.
window.ACTIVITY_ALBUM_FILES = $json;
"@

$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllText($outputPath, ($content.TrimEnd() + [Environment]::NewLine), $utf8WithoutBom)

Write-Host ""
Write-Host ("Album manifest updated: {0} image(s) in total." -f $totalCount) -ForegroundColor Green
Write-Host $outputPath
